apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ofgs-api-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    rules:
        - host: dfgs.dta32.my.id
          http:
              paths:
                  - path: /api(/|$)(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: ofgs-api-service
                            port:
                                number: 80
